### ISSUE TITLE
Incorrect formatting on Hadoop error message

### ISSUE THREAD

**Issue by amanshu** [SatelliteApplicationsCatapult/fulgurite#31] opened 2016-08-11 09:14 UTC
If the hadoop location can not be found the tests fail with the error:
'Error: Could not find or load main class Fileshadoop-2.6.0Could not write standard input into: Gradle Test Executor 5.'

This appears to be missing spaces in the middle...?

**Comment by emilyselwood** [comment] 2016-08-11 10:22
This appears to be caused by the fact that \ is an escape character in properties file. thus the paths are getting escaped in strange ways. I'll add some documentation about this to both the read me and the better error message I'm adding to deal with #29 and #30

**Comment by emilyselwood** [comment] 2016-08-11 11:47
Resolved with #33

**Closed as completed by emilyselwood** 2016-08-11 11:47 UTC
